{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Errors Rate (5xx)/s",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(event_booking_http_errors_total[5m])",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(event_booking_http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(event_booking_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(event_booking_http_requests_total[5m])",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  }
 ]
}