// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/booking/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ENUMS
type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_PENDING     BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 2
	BookingStatus_BOOKING_STATUS_CANCELLED   BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_CANCELLED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_CANCELLED":   3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_booking_booking_proto_enumTypes[0].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_api_v1_booking_booking_proto_enumTypes[0]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{0}
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Seats         int32                  `protobuf:"varint,4,opt,name=seats,proto3" json:"seats,omitempty"`
	Status        BookingStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=api.v1.booking.BookingStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Booking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Seats         int32                  `protobuf:"varint,3,opt,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateBookingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBookingRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookingResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CancelBookingRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_api_v1_booking_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_booking_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_booking_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookingsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListBookingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBookingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_api_v1_booking_booking_proto protoreflect.FileDescriptor

const file_api_v1_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/booking/booking.proto\x12\x0eapi.v1.booking\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd5\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05seats\x18\x04 \x01(\x05R\x05seats\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.api.v1.booking.BookingStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\x14CreateBookingRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05seats\x18\x03 \x01(\x05R\x05seats\"'\n" +
	"\x15CreateBookingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"^\n" +
	"\x13ListBookingsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset*\x87\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x032\xd7\x02\n" +
	"\x0eBookingService\x12\\\n" +
	"\rCreateBooking\x12$.api.v1.booking.CreateBookingRequest\x1a%.api.v1.booking.CreateBookingResponse\x12M\n" +
	"\rCancelBooking\x12$.api.v1.booking.CancelBookingRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\n" +
	"GetBooking\x12!.api.v1.booking.GetBookingRequest\x1a\x17.api.v1.booking.Booking\x12N\n" +
	"\fListBookings\x12#.api.v1.booking.ListBookingsRequest\x1a\x17.api.v1.booking.Booking0\x01B\x12Z\x10./api/v1/bookingb\x06proto3"

var (
	file_api_v1_booking_booking_proto_rawDescOnce sync.Once
	file_api_v1_booking_booking_proto_rawDescData []byte
)

func file_api_v1_booking_booking_proto_rawDescGZIP() []byte {
	file_api_v1_booking_booking_proto_rawDescOnce.Do(func() {
		file_api_v1_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_booking_booking_proto_rawDesc), len(file_api_v1_booking_booking_proto_rawDesc)))
	})
	return file_api_v1_booking_booking_proto_rawDescData
}

var file_api_v1_booking_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_booking_booking_proto_goTypes = []any{
	(BookingStatus)(0),            // 0: api.v1.booking.BookingStatus
	(*Booking)(nil),               // 1: api.v1.booking.Booking
	(*CreateBookingRequest)(nil),  // 2: api.v1.booking.CreateBookingRequest
	(*CreateBookingResponse)(nil), // 3: api.v1.booking.CreateBookingResponse
	(*CancelBookingRequest)(nil),  // 4: api.v1.booking.CancelBookingRequest
	(*GetBookingRequest)(nil),     // 5: api.v1.booking.GetBookingRequest
	(*ListBookingsRequest)(nil),   // 6: api.v1.booking.ListBookingsRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_api_v1_booking_booking_proto_depIdxs = []int32{
	0, // 0: api.v1.booking.Booking.status:type_name -> api.v1.booking.BookingStatus
	7, // 1: api.v1.booking.Booking.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: api.v1.booking.BookingService.CreateBooking:input_type -> api.v1.booking.CreateBookingRequest
	4, // 3: api.v1.booking.BookingService.CancelBooking:input_type -> api.v1.booking.CancelBookingRequest
	5, // 4: api.v1.booking.BookingService.GetBooking:input_type -> api.v1.booking.GetBookingRequest
	6, // 5: api.v1.booking.BookingService.ListBookings:input_type -> api.v1.booking.ListBookingsRequest
	3, // 6: api.v1.booking.BookingService.CreateBooking:output_type -> api.v1.booking.CreateBookingResponse
	8, // 7: api.v1.booking.BookingService.CancelBooking:output_type -> google.protobuf.Empty
	1, // 8: api.v1.booking.BookingService.GetBooking:output_type -> api.v1.booking.Booking
	1, // 9: api.v1.booking.BookingService.ListBookings:output_type -> api.v1.booking.Booking
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_booking_booking_proto_init() }
func file_api_v1_booking_booking_proto_init() {
	if File_api_v1_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_booking_booking_proto_rawDesc), len(file_api_v1_booking_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_booking_booking_proto_goTypes,
		DependencyIndexes: file_api_v1_booking_booking_proto_depIdxs,
		EnumInfos:         file_api_v1_booking_booking_proto_enumTypes,
		MessageInfos:      file_api_v1_booking_booking_proto_msgTypes,
	}.Build()
	File_api_v1_booking_booking_proto = out.File
	file_api_v1_booking_booking_proto_goTypes = nil
	file_api_v1_booking_booking_proto_depIdxs = nil
}
