syntax = "proto3";

package api.v1.booking;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "./api/v1/booking";

//ENUMS
enum BookingStatus {
    BOOKING_STATUS_UNSPECIFIED = 0;
    BOOKING_STATUS_PENDING = 1;
    BOOKING_STATUS_CONFIRMED = 2;
    BOOKING_STATUS_CANCELLED = 3;
}

//MESSAGES

message Booking {
  int64 id = 1;
  int64 event_id = 2;
  int64 user_id = 3;
  int32 seats = 4;
  BookingStatus status = 5;
  google.protobuf.Timestamp created_at = 6;
}


//Requests / Responses

message CreateBookingRequest {
  int64 event_id = 1;
  int64 user_id = 2;
  int32 seats = 3;
}

message CreateBookingResponse {
  int64 id = 1;
}

message CancelBookingRequest {
  int64 booking_id = 1;
}

message GetBookingRequest {
  int64 booking_id = 1;
}

message ListBookingsRequest {
  int64 event_id = 1;
  int32 limit = 2;
  int32 offset = 3;
}

// Service
service BookingService {
  // Create returns created id (matches REST 201 id)
  rpc CreateBooking(CreateBookingRequest) returns (CreateBookingResponse);

  // Cancel returns empty -> maps to HTTP 204
  rpc CancelBooking(CancelBookingRequest) returns (google.protobuf.Empty);

  // Get single booking
  rpc GetBooking(GetBookingRequest) returns (Booking);

  // List bookings for event (server streaming)
  rpc ListBookings(ListBookingsRequest) returns (stream Booking);
}